import type { Metadata } from "next";
import "./globals.css";
import  {lusitana}  from "./fonts/fonts";
import style from './page.module.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lusitana.className} ${style.body}`}>
        {children}
      </body>
    </html>
  );
}
